# Generated by Django 3.2.8 on 2021-10-07 08:01

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('period', models.IntegerField()),
                ('price', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('pay_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('pay_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pay_type', models.IntegerField()),
                ('remain', models.IntegerField()),
                ('end_date', models.DateField()),
                ('membership_id', models.IntegerField()),
                ('refund_date', models.DateTimeField(null=True)),
                ('status', models.IntegerField()),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
